apiVersion: ran.unisinos/v1alpha1
kind: RANPlacer
metadata:
  name: ranplacer-sample
  namespace: default
spec:
  # Add fields here
  coreIP: 10.233.100.151
  algorithm: ng-ran-model
  #  algorithm: example
  ruConfigMap: rus
  topologyConfigMap: topology
  resources:
    cu:
      cpu: 1
      memory: 2037Ki
    du:
      cpu: 1
      memory: 2037Ki
    ru:
      cpu: 1
      memory: 2037Ki
